name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.36
      - name: Setup Fluent CI CLI
        run: deno install -A -r https://cli.fluentci.io -n fluentci
      - name: Setup Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.1 sh
          sudo mv bin/dagger /usr/local/bin
          dagger version
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../src/dagger/runner.ts
        working-directory: example
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: tsirysndr
          SONAR_PROJECT_KEY: sonar-example
          SONAR_SOURCES: src,copybooks
